---
abstract: 'Perl interface to the GStreamer library'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::Depends: 0.205
  ExtUtils::MakeMaker: 0
  ExtUtils::PkgConfig: 1.07
  Glib: 1.180
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GStreamer
no_index:
  directory:
    - t
    - inc
    - xs
requires:
  ExtUtils::Depends: 0.205
  ExtUtils::PkgConfig: 1.07
  Glib: 1.180
version: 0.17
