--- #YAML:1.0
name:               GStreamer
version:            0.14
abstract:           Perl interface to the GStreamer library
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::Depends:    0.205
    ExtUtils::MakeMaker:  0
    ExtUtils::PkgConfig:  1.07
    Glib:                 1.180
requires:
    ExtUtils::Depends:    0.205
    ExtUtils::PkgConfig:  1.07
    Glib:                 1.180
no_index:
    directory:
        - t
        - inc
        - xs
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
