---
abstract: 'Perl interface to the GStreamer library'
author:
  - 'gtk2-perl Team <gtk-perl-list at gnome dot org>'
build_requires: {}
configure_requires:
  ExtUtils::Depends: 0.205
  ExtUtils::PkgConfig: 1.07
  Glib: 1.180
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GStreamer
no_index:
  directory:
    - t
    - inc
    - xs
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=GStreamer
  homepage: http://gtk2-perl.sourceforge.net
  license: http://www.gnu.org/licenses/lgpl-2.1.html
  repository: git://git.gnome.org/perl-GStreamer
  x_MailingList: https://mail.gnome.org/mailman/listinfo/gtk-perl-list
version: 0.18
